version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjsauthdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: